/**
 * Running a snippet of GLSL and reading its answers back.
 *
 * `basics/` is a mathematics library, and its functions have properties that
 * are either true or false — a derivative either matches the function it
 * claims to differentiate or it does not; a distance to the nearest point is
 * either 1-Lipschitz or it is not. Those are the bugs that matter most and the
 * ones eyes are worst at: an analytic derivative with a transposed matrix or a
 * flipped sign produces a picture that looks entirely plausible and is wrong
 * everywhere.
 *
 * The golden reference images cannot help here. They pin what a piece USED to
 * look like, which catches change and says nothing about correctness — a
 * derivative that was wrong when the reference was made stays wrong and green.
 *
 * So: write the snippet into a temporary artwork directory, let the ordinary
 * pipeline compile it, render it, and read the pixels. It runs the real GLSL
 * through the real include resolver and the real preamble on the real driver,
 * which is the only way to test a shader function as it is actually used.
 *
 * OUTPUT IS EIGHT-BIT. The resolve pass divides by the sample count and encodes
 * to sRGB, so a probe cannot read a float back. It therefore answers PREDICATES
 * — 1.0 or 0.0 per channel, three per pixel — which survive that path exactly
 * (0 stays 0 and 1 stays 255 through any monotonic encode). Three thresholds
 * per probe turns out to be more useful than one float anyway: it says not just
 * whether the property holds but how well.
 */
import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import type { Image } from './png.ts';
import { ROOT, type Session } from './session.ts';

/**
 * Probes get a FRESH DIRECTORY EACH TIME, in a numeric range no artwork uses.
 *
 * Reusing one directory looked tidy and was wrong: Vite caches a module's
 * transform, its watcher notices the rewrite asynchronously, and a probe that
 * navigated immediately after writing could be served the PREVIOUS probe's
 * compiled shader. Measured, with three probes whose answers cannot be
 * confused — all-true, all-false, half — the third came back with the second's
 * answer. A path Vite has never seen cannot be stale.
 *
 * That race is worse than an ordinary bug because of what probes are for. They
 * mostly pass, and a stale pass is indistinguishable from a real one, so a
 * whole suite can report properties it never actually checked. The marker below
 * exists so that even if some future caching returns the wrong shader, it
 * cannot be mistaken for an answer.
 */
let probeSeq = 0;

export interface ProbeSource {
  /** basics/ paths to #include, e.g. ['noise/curl.glsl']. */
  includes: string[];
  /**
   * The body of `mainImage`. `pix` is the integer pixel coordinate (the
   * supersampling jitter is floored away, so a probe sees exact indices), and
   * `n` is the grid size. Assign the three predicates to `fragColor.rgb`.
   */
  body: string;
}

export interface ProbeCounts {
  total: number;
  /** Pixels where each channel came back 0 — the property failed at that point. */
  failed: [number, number, number];
  /** First failing pixel, for a message that says where. */
  firstFailure: { x: number; y: number; rgb: [number, number, number] } | null;
}

/**
 * A small non-zero integer derived from the probe's own source.
 *
 * Written as BITS into the red channel of the first eight pixels and checked on
 * read-back, so that a probe answering with some OTHER probe's shader is a hard
 * error rather than a plausible number.
 *
 * The obvious channel was alpha, and it does not work: the context is created
 * with `alpha: false`, so the drawing buffer has none and read-back is always
 * 255. The check caught that on its first run, which is the argument for having
 * it. Bits in red work because they are predicates like everything else a probe
 * returns, and 0 and 1 survive the sRGB encode exactly where an arbitrary value
 * would not.
 */
function marker(text: string): number {
  let h = 2166136261;
  for (let i = 0; i < text.length; i++) {
    h ^= text.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return ((h >>> 0) % 251) + 1; // 1..251, away from both ends
}

/** Pixels at the start of row 0 reserved for the identity stamp. */
export const PROBE_STAMP_PIXELS = 8;

function source(p: ProbeSource, mark: number): string {
  return [
    '// Generated by tools/probe.ts. If this file is on disk, a probe crashed.',
    ...p.includes.map((i) => `#include "${i}"`),
    '',
    'void mainImage(out vec4 fragColor, in vec2 fragCoord) {',
    '    // Exact integer pixel: the sampling loop jitters fragCoord by [0,1).',
    '    vec2 pix = floor(fragCoord);',
    '    float n = uFullRes.x;',
    '    vec3 ok = vec3(0.0);',
    p.body.replace(/^/gm, '    '),
    '    // Identity stamp, overwriting the first eight pixels of GL row 0 —',
    '    // which readPixels flips to the LAST row of the returned image.',
    '    // countFailures skips them; see marker() in tools/probe.ts.',
    `    if (pix.y < 0.5 && pix.x < ${PROBE_STAMP_PIXELS}.0 - 0.5) {`,
    `        int bit = (${mark} >> int(pix.x)) & 1;`,
    '        ok = vec3(float(bit));',
    '    }',
    '    fragColor = vec4(ok, 1.0);',
    '}',
    '',
  ].join('\n');
}

/**
 * Render one probe at `size` x `size` and return its pixels.
 *
 * The directory is removed in a finally, and its id is outside the range real
 * artwork uses, so a crash leaves something loud rather than something that
 * quietly joins the gallery.
 */
export async function runProbe(s: Session, p: ProbeSource, size: number): Promise<Image> {
  const id = `9${String(probeSeq++ % 100).padStart(2, '0')}`;
  const dir = path.join(ROOT, 'artwork', `${id}-probe`);
  const mark = marker(JSON.stringify(p));
  const src = source(p, mark);
  try {
    mkdirSync(dir, { recursive: true });
    writeFileSync(path.join(dir, 'meta.json'),
      `${JSON.stringify({ id, slug: 'probe', title: 'Probe' }, null, 2)}\n`);
    writeFileSync(path.join(dir, 'main.frag'), src);

    await s.open(`?p=${id}`);
    const err = await s.page.evaluate(() => window.__pa.error);
    if (err) throw new Error(`probe failed to compile:\n${err}`);

    const bytes = await s.page.evaluate(
      (n: number) => window.__pa.renderAt(n, n, 0, 1),
      size,
    );
    const data = Uint8Array.from(bytes);

    // The identity check. If this ever fires, the answer below belongs to some
    // other probe and every conclusion drawn from it would be fiction.
    // The stamp is written at gl_FragCoord.y == 0, and readPixels returns
    // top-left origin, so it comes back on the bottom row. Reading the top row
    // instead is what the first version did, and the check reported 255 —
    // every bit set — rather than quietly passing.
    const stampRow = (size - 1) * size * 4;
    let got = 0;
    for (let b = 0; b < PROBE_STAMP_PIXELS; b++) {
      if (data[stampRow + b * 4] > 127) got |= 1 << b;
    }
    if (got !== mark) {
      throw new Error(
        `probe identity check failed: expected marker ${mark}, read ${got}. ` +
          'The page rendered a different shader than this probe wrote.',
      );
    }
    return { width: size, height: size, data };
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

/** Count where each predicate channel came back false. */
export function countFailures(image: Image): ProbeCounts {
  const failed: [number, number, number] = [0, 0, 0];
  let first: ProbeCounts['firstFailure'] = null;
  // Skip the identity stamp on the bottom row: those pixels carry the marker.
  const stampStart = (image.height - 1) * image.width * 4;
  const stampEnd = stampStart + PROBE_STAMP_PIXELS * 4;
  for (let i = 0; i < image.data.length; i += 4) {
    if (i >= stampStart && i < stampEnd) continue;
    const rgb: [number, number, number] = [image.data[i], image.data[i + 1], image.data[i + 2]];
    let any = false;
    for (let c = 0; c < 3; c++) {
      if (rgb[c] < 128) {
        failed[c]++;
        any = true;
      }
    }
    if (any && !first) {
      const px = i / 4;
      first = { x: px % image.width, y: Math.floor(px / image.width), rgb };
    }
  }
  return { total: image.data.length / 4 - PROBE_STAMP_PIXELS, failed, firstFailure: first };
}

/** One line describing what a probe found, for a check's detail text. */
export function describe(c: ProbeCounts, labels: [string, string, string]): string {
  const parts = labels.map((l, i) =>
    `${l}: ${c.total - c.failed[i]}/${c.total}`);
  const at = c.firstFailure
    ? `  first failure at (${c.firstFailure.x}, ${c.firstFailure.y})`
    : '';
  return parts.join('  ') + at;
}
